repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.1.0
    hooks:
      - id: pyupgrade
        args: ['--py36-plus']
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.8.2
    hooks:
      - id: reorder-python-imports
        name: Reorder Python imports (src, tests)
        files: "^(?!examples/)"
        args: [ "--application-directories", "src" ]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: ["-l", "119"]
  - repo: https://github.com/PyCQA/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==22.7.1
          - flake8-implicit-str-concat
        exclude: alembic
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-byte-order-marker
      - id: trailing-whitespace
      - id: end-of-file-fixer
#  - repo: https://github.com/PyCQA/pylint
#    rev: v2.15.5
#    hooks:
#      - id: pylint
#        args: ["-rn", "-sn"]
