"""revision

Revision ID: f423638c66f3
Revises: 
Create Date: 2022-11-21 01:43:28.618971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f423638c66f3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "participant",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table("team", sa.Column("name", sa.String(), nullable=False), sa.PrimaryKeyConstraint("name"))
    op.create_table(
        "fixture",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("home_team_name", sa.String(), nullable=False),
        sa.Column("away_team_name", sa.String(), nullable=False),
        sa.Column("home_team_goals", sa.Integer(), nullable=True),
        sa.Column("away_team_goals", sa.Integer(), nullable=True),
        sa.Column("home_team_won", sa.Boolean(), nullable=True),
        sa.Column("away_team_won", sa.Boolean(), nullable=True),
        sa.Column("venue_name", sa.String(), nullable=False),
        sa.Column("venue_city", sa.String(), nullable=False),
        sa.Column("kick_off", sa.DateTime(), nullable=False),
        sa.Column("round", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["away_team_name"],
            ["team.name"],
        ),
        sa.ForeignKeyConstraint(
            ["home_team_name"],
            ["team.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "team_and_participant",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("team_name", sa.String(), nullable=False),
        sa.Column("participant_name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["participant_name"],
            ["participant.name"],
        ),
        sa.ForeignKeyConstraint(
            ["team_name"],
            ["team.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("team_and_participant")
    op.drop_table("fixture")
    op.drop_table("team")
    op.drop_table("participant")
    # ### end Alembic commands ###
