"""db models

Revision ID: deb4f5454019
Revises:
Create Date: 2022-12-04 01:20:18.300971

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "deb4f5454019"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "participant",
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("telegram_user_id"),
    )
    op.create_table(
        "team",
        sa.Column("football_api_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("football_api_id"),
    )
    op.create_table(
        "draw_mapping",
        sa.Column("team_football_api_id", sa.Integer(), nullable=False),
        sa.Column("participant_telegram_user_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["participant_telegram_user_id"],
            ["participant.telegram_user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_football_api_id"],
            ["team.football_api_id"],
        ),
        sa.PrimaryKeyConstraint("team_football_api_id", "participant_telegram_user_id"),
        sa.UniqueConstraint("team_football_api_id", "participant_telegram_user_id", name="one_team_per_participant"),
    )
    op.create_table(
        "fixture",
        sa.Column("football_api_id", sa.Integer(), nullable=False),
        sa.Column("home_team_football_api_id", sa.Integer(), nullable=False),
        sa.Column("away_team_football_api_id", sa.Integer(), nullable=False),
        sa.Column("home_team_goals", sa.Integer(), nullable=True),
        sa.Column("away_team_goals", sa.Integer(), nullable=True),
        sa.Column("home_team_won", sa.Boolean(), nullable=True),
        sa.Column("away_team_won", sa.Boolean(), nullable=True),
        sa.Column("venue_name", sa.String(), nullable=False),
        sa.Column("venue_city", sa.String(), nullable=False),
        sa.Column("kick_off", sa.DateTime(), nullable=False),
        sa.Column("round", sa.String(), nullable=False),
        sa.Column("home_goals_halftime", sa.Integer(), nullable=True),
        sa.Column("away_goals_halftime", sa.Integer(), nullable=True),
        sa.Column("home_goals_fulltime", sa.Integer(), nullable=True),
        sa.Column("away_goals_fulltime", sa.Integer(), nullable=True),
        sa.Column("away_goals_extratime", sa.Integer(), nullable=True),
        sa.Column("home_goals_extratime", sa.Integer(), nullable=True),
        sa.Column("home_goals_penalties", sa.Integer(), nullable=True),
        sa.Column("away_goals_penalties", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["away_team_football_api_id"],
            ["team.football_api_id"],
        ),
        sa.ForeignKeyConstraint(
            ["home_team_football_api_id"],
            ["team.football_api_id"],
        ),
        sa.PrimaryKeyConstraint("football_api_id"),
    )
    op.create_table(
        "player",
        sa.Column("football_api_id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("team_football_api_id", sa.Integer(), nullable=False),
        sa.Column("yellow_cards", sa.Integer(), nullable=True),
        sa.Column("yellow_then_red_cards", sa.Integer(), nullable=True),
        sa.Column("red_cards", sa.Integer(), nullable=True),
        sa.Column("goals", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["team_football_api_id"],
            ["team.football_api_id"],
        ),
        sa.PrimaryKeyConstraint("football_api_id"),
    )
    op.create_table(
        "fixture_event",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("fixture_football_api_id", sa.Integer(), nullable=False),
        sa.Column("time_elapsed_min", sa.Integer(), nullable=False),
        sa.Column("time_elapsed_extra_min", sa.Integer(), nullable=True),
        sa.Column("team_football_api_id", sa.Integer(), nullable=False),
        sa.Column("player_football_api_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("detail", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fixture_football_api_id"],
            ["fixture.football_api_id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_football_api_id"],
            ["player.football_api_id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_football_api_id"],
            ["team.football_api_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "fixture_football_api_id",
            "time_elapsed_min",
            "time_elapsed_extra_min",
            "team_football_api_id",
            "player_football_api_id",
            "type",
            "detail",
            name="one_event_per_min_per_team_per_player_per_type",
        ),
    )
    op.create_table(
        "sweepstake_category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("reward_amount", sa.Integer(), nullable=False),
        sa.Column("winning_team_football_api_id", sa.Integer(), nullable=True),
        sa.Column("winning_player_football_api_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["winning_player_football_api_id"],
            ["player.football_api_id"],
        ),
        sa.ForeignKeyConstraint(
            ["winning_team_football_api_id"],
            ["team.football_api_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sweepstake_category")
    op.drop_table("fixture_event")
    op.drop_table("player")
    op.drop_table("fixture")
    op.drop_table("draw_mapping")
    op.drop_table("team")
    op.drop_table("participant")
    # ### end Alembic commands ###
