"""db models

Revision ID: 769f98b79f5b
Revises:
Create Date: 2022-11-21 21:49:43.076745

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "769f98b79f5b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "participant",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table("team", sa.Column("name", sa.String(), nullable=False), sa.PrimaryKeyConstraint("name"))
    op.create_table(
        "fixture",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("football_api_id", sa.String(), nullable=False),
        sa.Column("home_team_name", sa.String(), nullable=False),
        sa.Column("away_team_name", sa.String(), nullable=False),
        sa.Column("home_team_goals", sa.Integer(), nullable=True),
        sa.Column("away_team_goals", sa.Integer(), nullable=True),
        sa.Column("home_team_won", sa.Boolean(), nullable=True),
        sa.Column("away_team_won", sa.Boolean(), nullable=True),
        sa.Column("venue_name", sa.String(), nullable=False),
        sa.Column("venue_city", sa.String(), nullable=False),
        sa.Column("kick_off", sa.DateTime(), nullable=False),
        sa.Column("round", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["away_team_name"],
            ["team.name"],
        ),
        sa.ForeignKeyConstraint(
            ["home_team_name"],
            ["team.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "team_and_participant",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("team_name", sa.String(), nullable=False),
        sa.Column("participant_name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["participant_name"],
            ["participant.name"],
        ),
        sa.ForeignKeyConstraint(
            ["team_name"],
            ["team.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("team_name", "participant_name", name="one_team_per_person"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("team_and_participant")
    op.drop_table("fixture")
    op.drop_table("team")
    op.drop_table("participant")
    # ### end Alembic commands ###
